build uncached on cpu8 with -j16 [skip-vdc] [skip-docs] [skip-rapids]

diff --git a/.github/actions/workflow-run-job-linux/action.yml b/.github/actions/workflow-run-job-linux/action.yml
--- a/.github/actions/workflow-run-job-linux/action.yml
+++ b/.github/actions/workflow-run-job-linux/action.yml
@@ -38,6 +38,7 @@ inputs:
   host:
     description: "The host compiler to use when selecting a devcontainer."
     required: true
+  # This token must have the "read:enterprise" scope
   dist-token:
     description: "The token used to authenticate with the sccache-dist build cluster."
     required: false
@@ -98,7 +99,7 @@ runs:
         #! /usr/bin/env bash
         set -eo pipefail
         echo -e "\e[1;34mRunning as '$(whoami)' user in $(pwd):\e[0m"
-        echo -e "\e[1;34mBuild cluster: $(sccache --dist-status)\e[0m"
+        echo -e "\e[1;34mBuild cluster: $(sccache --dist-status; echo "exit code: $?")\e[0m"
         echo -e "\e[1;34m${COMMAND}\e[0m"
         eval "${COMMAND}" || exit_code=$?
         if [ ! -z "$exit_code" ]; then
@@ -138,54 +139,63 @@ runs:
 
         chmod 0600 "$RUNNER_TEMP/.aws/credentials"
 
-        __w_HOST="$(dirname "$(dirname "${{github.workspace}}")")"
-
-        host_path() {
-          sed "s@/__w@$__w_HOST@" <<< "$1"
-        }
-
-        RUNNER_TEMP_HOST="$(host_path "$RUNNER_TEMP")"
-
         declare -a extra_launch_args=()
 
-        if test "${DIST_TOKEN:+x}" = x; then
-          mkdir -p "$RUNNER_TEMP/.config/sccache"
+        OS="$(uname -s)"
+        CPUS="$(nproc --all)"
+        ARCH="$(dpkg --print-architecture)"
 
+        if test "$ARCH" = amd64 && test -n "${DIST_TOKEN:+x}"; then
           mkdir -p "$RUNNER_TEMP/bin"
+          mkdir -p "$RUNNER_TEMP/.config/sccache"
 
           # Download newer sccache binary
           curl -fsSL \
-            "https://github.com/trxcllnt/sccache/releases/download/v0.8.3-rapids.12/sccache-v0.8.3-rapids.12-$(uname -m)-unknown-linux-musl.tar.gz" \
+            "https://github.com/trxcllnt/sccache/releases/download/v0.8.3-rapids.14/sccache-v0.8.3-rapids.14-$(uname -m)-unknown-linux-musl.tar.gz" \
           | tar -C "$RUNNER_TEMP/bin" -zf - --wildcards --strip-components=1 -x '*/sccache'
 
-          chmod 0755 "$RUNNER_TEMP/bin/sccache"
-
-          CPUS="$(nproc --all)"
-          OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
-          ARCH="$(dpkg --print-architecture | awk -F'-' '{print $NF}')"
-
+          # Configure sccache client to talk to the build cluster
           cat <<EOF > "$RUNNER_TEMP/.config/sccache/config"
         [cache.disk]
         size = 0
         [cache.disk.preprocessor_cache_mode]
         use_preprocessor_cache_mode = false
         [dist]
-        scheduler_url = "https://${ARCH}.${OS}.sccache-dist.gha-runners.nvidia.com"
+        scheduler_url = "https://${ARCH}.${OS,,}.sccache-dist.gha-runners.nvidia.com"
         [dist.auth]
         type = "token"
-        # Token must have the "read:enterprise" scope
         token = "${DIST_TOKEN}"
         EOF
 
           chmod 0664 "$RUNNER_TEMP/.config/sccache/config"
 
           extra_launch_args+=(
-            # --env "SCCACHE_RECACHE=1"
-            # --env "SCCACHE_NO_CACHE=1"
-            --env "PARALLEL_LEVEL=$((CPUS * 2))"
+            # Don't cache anything yet
+            --env "SCCACHE_NO_CACHE=1"
+
+            # When we do cache, use a separate namespace
             --env "SCCACHE_S3_KEY_PREFIX=cccl-sccache-dist-test"
-            --volume "$RUNNER_TEMP_HOST/.config:/root/.config:ro"
-            --volume "$RUNNER_TEMP_HOST/bin/sccache:/usr/bin/sccache:ro"
+
+            # Compile device objects in parallel
+            --env "NVCC_APPEND_FLAGS=-t=100"
+
+            # Over-subscribe -j to keep the build cluster busy
+            --env "PARALLEL_LEVEL=$((CPUS * 2))"
+
+            # Retry failed builds 5 times before building locally
+            --env "SCCACHE_DIST_RETRY_LIMIT=5"
+
+            # Allow time for the build cluster to respond to requests
+            --env "SCCACHE_DIST_CONNECT_TIMEOUT=30"
+            --env "SCCACHE_DIST_REQUEST_TIMEOUT=1200"
+
+            # Instruct sccache to write debug logs to a file we can upload
+            --env "SCCACHE_SERVER_LOG=sccache=debug"
+            --env "SCCACHE_ERROR_LOG=/home/coder/cccl/sccache.log"
+
+            # Mount in sccache client config and updated binary
+            --volume "${{runner.temp}}/.config:/root/.config:ro"
+            --volume "${{runner.temp}}/bin/sccache:/usr/bin/sccache:ro"
           )
         fi
 
@@ -214,39 +224,60 @@ runs:
           --env "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" \
           --env "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" \
           --env "GITHUB_STEP_SUMMARY=$GITHUB_STEP_SUMMARY" \
-          --volume "$RUNNER_TEMP_HOST/ci.sh:/ci.sh:ro" \
-          --volume "$RUNNER_TEMP_HOST/.aws:/root/.aws" \
-          --volume "$__w_HOST:/__w" \
+          --volume "${{runner.temp}}/ci.sh:/ci.sh:ro" \
+          --volume "${{runner.temp}}/.aws:/root/.aws" \
+          --volume "$(dirname "$(dirname "${{github.workspace}}")"):/__w" \
           "${extra_launch_args[@]}" \
           -- /ci.sh
 
-    - name: Prepare job artifacts
+    - if: ${{ always() }}
+      name: Create job artifact dir
+      shell: bash --noprofile --norc -euo pipefail {0}
+      run: |
+        result_dir="jobs/${{inputs.id}}"
+        mkdir -p "$result_dir"
+        echo "result_dir=$result_dir" >> "$GITHUB_ENV"
+
+    - if: ${{ success() }}
+      name: Record job success
+      shell: bash --noprofile --norc -euo pipefail {0}
+      run: |
+        touch "$result_dir/success"
+
+    - if: ${{ always() }}
+      name: Prepare job artifacts
       shell: bash --noprofile --norc -euo pipefail {0}
       run: |
         echo "Prepare job artifacts"
-        result_dir="jobs/${{inputs.id}}"
-        mkdir -p "$result_dir"
 
-        touch "$result_dir/success"
+        # chmod all temp contents 777 so the runner can delete them
+        find "$RUNNER_TEMP/" -exec chmod 0777 {} \;
 
         # Finds a matching file in the repo directory and copies it to the results directory.
         find_and_copy() {
-          filename="$1"
-          filepath="$(find ${{github.event.repository.name}} -name "${filename}" -print -quit)"
+          pat="$1"
+          dir="${{github.event.repository.name}}"
+          filepath="$(find "$dir/" -type f -path "$dir/$pat" -print -quit)"
           if [[ -z "$filepath" ]]; then
-            echo "${filename} does not exist in repo directory."
+            echo "File with pattern '$dir/$pat' does not exist in repo directory."
             return 1
           fi
           cp -v "$filepath" "$result_dir"
         }
 
-        find_and_copy "sccache_stats.json" || true # Ignore failures
+        # Ignore failures
+        find_and_copy "sccache.log" || true
+        find_and_copy "build/*/.ninja_log" || true
+        find_and_copy "build/*/build.ninja" || true
+        find_and_copy "build/*/rules.ninja" || true
+        find_and_copy "build/*/sccache_stats.json" || true
 
         echo "::group::Job artifacts"
         tree "$result_dir"
         echo "::endgroup::"
 
-    - name: Upload job artifacts
+    - if: ${{ always() }}
+      name: Upload job artifacts
       uses: actions/upload-artifact@v4
       with:
         name: jobs-${{inputs.id}}
