bump sccache version [skip-vdc] [skip-docs] [skip-rapids]

diff --git a/.github/actions/workflow-run-job-linux/action.yml b/.github/actions/workflow-run-job-linux/action.yml
--- a/.github/actions/workflow-run-job-linux/action.yml
+++ b/.github/actions/workflow-run-job-linux/action.yml
@@ -100,7 +100,7 @@ runs:
         #! /usr/bin/env bash
         set -eo pipefail
         echo -e "\e[1;34mRunning as '$(whoami)' user in $(pwd):\e[0m"
-        echo -e "\e[1;34mBuild cluster:\n$(sccache --dist-status | jq -r '.SchedulerStatus as [$x, $y] | [$x, ($y | {assigned, active, num_cpus, num_servers} | tojson), ($y.servers | to_entries | sort_by(.key) | map(.key as $k | .value | {assigned, active, server: $k} | tojson) | join("\n"))] | join("\n")')\e[0m"
+        echo -e "\e[1;34mBuild cluster:\n$(sccache --dist-status | jq -r '.SchedulerStatus as [$x, $y] | [$x, ($y | {num_servers, num_cpus, num_jobs: (.num_jobs_running + .num_jobs_pending)} | tojson), ($y.servers | to_entries | sort_by(.key) | map(.key as $k | .value | {num_cpus, num_jobs: (.num_jobs_running + .num_jobs_pending), id: $k} | tojson) | join("\n"))] | join("\n")')\e[0m"
         echo -e "\e[1;34m${COMMAND}\e[0m"
         eval "${COMMAND}" || exit_code=$?
         if [ ! -z "$exit_code" ]; then
@@ -166,8 +166,10 @@ runs:
         # Everything should be cached for test jobs.
         not_test_job="$(grep -q '"./ci/test_' <<< "$COMMAND" || echo $?)"
 
-        # Temporary: don't use sccache-dist for clang-cuda until
-        # sccache packages up a correct toolchain for the server
+        # Temporary: don't use sccache-dist for NVHPC, OneAPI, or clang-cuda
+        # until sccache packages up a correct toolchain for the server
+        not_nvhpc="$(grep -q 'nvhpc' <<< "${{inputs.host}}" || echo $?)"
+        not_oneapi="$(grep -q 'oneapi' <<< "${{inputs.host}}" || echo $?)"
         not_clang_cuda="$(grep -q '\-cuda "clang' <<< "$COMMAND" || echo $?)"
 
         # If a test job, over-subscribe -j to download more cache objects at once
@@ -182,15 +184,17 @@ runs:
           )
         fi
 
-        # If this is not a test job, and not a clang-cuda job, use the build cluster
-        if test -n "${not_test_job:+x}" \
+        # If this is not a test job and not one of the excluded compilers, use the build cluster
+        if test -n "${not_nvhpc:+x}" \
+        && test -n "${not_oneapi:+x}" \
+        && test -n "${not_test_job:+x}" \
         && test -n "${not_clang_cuda:+x}" \
         && test -n "${DIST_TOKEN:+x}"; then
 
           # Download newer sccache binary
           mkdir -p "$RUNNER_TEMP/bin"
           curl -fsSL \
-            "https://github.com/trxcllnt/sccache/releases/download/v0.8.3-rapids.64/sccache-v0.8.3-rapids.64-$(uname -m)-unknown-linux-musl.tar.gz" \
+            "https://github.com/trxcllnt/sccache/releases/download/v0.9.0-rapids.19/sccache-v0.9.0-rapids.19-$(uname -m)-unknown-linux-musl.tar.gz" \
           | tar -C "$RUNNER_TEMP/bin" -zf - --wildcards --strip-components=1 -x '*/sccache'
 
           # Configure sccache client to talk to the build cluster
@@ -211,14 +215,14 @@ runs:
 
             # Over-subscribe -j to keep the build cluster busy
             # --env "PARALLEL_LEVEL=$((CPUS * 2))"
-            --env "PARALLEL_LEVEL=64"
+            # --env "PARALLEL_LEVEL=64"
 
-            # Retry failed builds 10 times before building locally
-            --env "SCCACHE_DIST_RETRY_LIMIT=10"
+            # Retry failed builds 1 time before building locally
+            --env "SCCACHE_DIST_RETRY_LIMIT=1"
 
             # Build cluster connect and request timeouts
-            --env "SCCACHE_DIST_CONNECT_TIMEOUT=30"
-            --env "SCCACHE_DIST_REQUEST_TIMEOUT=720"
+            --env "SCCACHE_DIST_CONNECT_TIMEOUT=10"
+            --env "SCCACHE_DIST_REQUEST_TIMEOUT=1200"
 
             # Instruct sccache to write debug logs to a file we can upload
             --env "SCCACHE_SERVER_LOG=sccache=debug"
